version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    ports:
      - 15672:15672
      - 5672:5672

  postgres-1:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "microservice"
      POSTGRES_USER: "microserviceAdmin"
      POSTGRES_PASSWORD: "microserviceAdminPassword"
    volumes:
      - ./sql/postgresql-1:/docker-entrypoint-initdb.d  
    ports:
      - "5432:5432"
  
  postgres-2:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "microservice"
      POSTGRES_USER: "microserviceAdmin"
      POSTGRES_PASSWORD: "microserviceAdminPassword"
    volumes:
      - ./sql/postgresql-2:/docker-entrypoint-initdb.d  
    ports:
      - "5433:5432"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PORT=6379
  
  # gateway:
  #   image: microservice.gateway:latest
  #   ports:
  #     - "33331:80"
  #   depends_on:
  #     - postgres
  #     - redis
  
  # userapi-1:
  #   image: microservice.userapi:latest
  #   ports:
  #     - "33333:80"
  #   depends_on:
  #     - postgres
  #     - redis

  # userapi-2:
  #   image: microservice.userapi:latest
  #   ports:
  #     - "33334:80"
  #   depends_on:
  #     - postgres
  #     - redis

  # itemapi:
  #   image: microservice.itemapi:latest
  #   ports:
  #     - "33335:80"
  #   depends_on:
  #     - postgres
  #     - redis
